name       : gnupg
version    : 2.0.28
release    : 5
source     :
    - ftp://ftp.gnupg.org/gcrypt/gnupg/gnupg-2.0.28.tar.bz2 : ce092ee4ab58fd19b9fb34a460c07b06c348f4360dd5dd4886d041eb521a534c
license    : GPL-3.0
summary    : Complete and free implementation of OpenPGP
description: |
    GnuPG is a complete and free implementation of OpenPGP standard as defined by RFC4880. It allows encryption and signing of data and communications, a key management system, and access modules for public key directories.
clang : no
builddeps  :
    - bzip2-devel
    - libassuan-devel
    - libgcrypt-devel
    - libgpg-error
    - libksba-devel
    - libpth-devel
    - pinentry
setup      : |
    %configure --libexecdir=%libdir%/GnuPG --enable-symcryptrun --enable-gpgtar
build      : |
    %make
install    : |
    %make_install DESTDIR=$installdir
    ln -s $installdir/usr/bin/gpg2 $installdir/usr/bin/gpg
