name       : gnupg
version    : 2.2.13
release    : 24
source     :
    - https://gnupg.org/ftp/gcrypt/gnupg/gnupg-2.2.13.tar.bz2 : 76c787a955f9e6e0ead47c9be700bfb9d454f955a7b7c7e697aa719bac7b11d8
license    : GPL-3.0-or-later
summary    : Complete and free implementation of OpenPGP
component  : security
description: |
    GnuPG is a complete and free implementation of OpenPGP standard as defined by RFC4880. It allows encryption and signing of data and communications, a key management system, and access modules for public key directories.
builddeps  :
    - pkgconfig(gnutls)
    - pkgconfig(sqlite3)
    - bzip2-devel
    - libassuan-devel
    - libgcrypt-devel
    - libgpg-error-devel
    - libksba-devel
    - npth-devel
    - pinentry
rundeps    :
    - pinentry
setup      : |
    %configure \
    --enable-symcryptrun \
    --enable-gpgtar \
    --enable-all-tests
build      : |
    %make
install    : |
    %make_install DESTDIR=$installdir
    ln -s /usr/bin/gpg $installdir/usr/bin/gpg2
check      : |
    # If tests last too long, you can remove --enable-all-tests
    %make check
