name       : gnupg
version    : 2.2.27
release    : 38
source     :
    - https://gnupg.org/ftp/gcrypt/gnupg/gnupg-2.2.27.tar.bz2 : 34e60009014ea16402069136e0a5f63d9b65f90096244975db5cea74b3d02399
license    : GPL-3.0-or-later
summary    : Complete and free implementation of OpenPGP
component  : security
description: |
    GnuPG is a complete and free implementation of OpenPGP standard as defined by RFC4880. It allows encryption and signing of data and communications, a key management system, and access modules for public key directories.
builddeps  :
    - pkgconfig(gnutls)
    - pkgconfig(ksba)
    - pkgconfig(libassuan)
    - pkgconfig(libgcrypt)
    - pkgconfig(sqlite3)
    - bzip2-devel
    - libgpg-error-devel
    - npth-devel
    - pinentry
rundeps    :
    - pinentry
setup      : |
    %configure \
    --enable-symcryptrun \
    --enable-gpgtar \
    --enable-all-tests
build      : |
    %make
install    : |
    %make_install DESTDIR=$installdir
    ln -s /usr/bin/gpg $installdir/usr/bin/gpg2
check      : |
    # If tests last too long, you can remove --enable-all-tests
    %make check
