name       : gnupg
version    : 2.0.30
release    : 10
source     :
    - https://www.gnupg.org/ftp/gcrypt/gnupg/gnupg-2.0.30.tar.bz2 : e329785a4f366ba5d72c2c678a7e388b0892ac8440c2f4e6810042123c235d71
license    : GPL-3.0
summary    : Complete and free implementation of OpenPGP
description: |
    GnuPG is a complete and free implementation of OpenPGP standard as defined by RFC4880. It allows encryption and signing of data and communications, a key management system, and access modules for public key directories.
clang      : no
builddeps  :
    - bzip2-devel
    - libassuan-devel
    - libgcrypt-devel
    - libgpg-error
    - libksba-devel
    - libpth-devel
    - pinentry
rundeps    :
    - pinentry
setup      : |
    %configure --enable-symcryptrun --enable-gpgtar --enable-standard-socket
build      : |
    %make
install    : |
    %make_install DESTDIR=$installdir
    ln -s /usr/bin/gpg2 $installdir/usr/bin/gpg
