name       : gnupg
version    : 2.2.7
release    : 18
source     :
    - https://gnupg.org/ftp/gcrypt/gnupg/gnupg-2.2.7.tar.bz2 : d95b361ee6ef7eff86af40c8c72bf9313736ac9f7010d6604d78bf83818e976e
license    : GPL-3.0
summary    : Complete and free implementation of OpenPGP
component  : security
description: |
    GnuPG is a complete and free implementation of OpenPGP standard as defined by RFC4880. It allows encryption and signing of data and communications, a key management system, and access modules for public key directories.
builddeps  :
    - pkgconfig(gnutls)
    - pkgconfig(sqlite3)
    - bzip2-devel
    - libassuan-devel
    - libgcrypt-devel
    - libgpg-error-devel
    - libksba-devel
    - npth-devel
    - pinentry
rundeps    :
    - pinentry
setup      : |
    %configure \
    --enable-symcryptrun \
    --enable-gpgtar \
    --enable-all-tests
build      : |
    %make
install    : |
    %make_install DESTDIR=$installdir
    ln -s /usr/bin/gpg $installdir/usr/bin/gpg2
check      : |
    # If tests last too long, you can remove --enable-all-tests
    %make check
