name       : gnupg
version    : 2.0.29
release    : 8
source     :
    - https://www.gnupg.org/ftp/gcrypt/gnupg/gnupg-2.0.29.tar.bz2 : 68ed6b386ba78425b05a60e8ee22785ff0fef190bdc6f1c612f19a58819d4ac9
license    : GPL-3.0
summary    : Complete and free implementation of OpenPGP
description: |
    GnuPG is a complete and free implementation of OpenPGP standard as defined by RFC4880. It allows encryption and signing of data and communications, a key management system, and access modules for public key directories.
clang : no
builddeps  :
    - bzip2-devel
    - libassuan-devel
    - libgcrypt-devel
    - libgpg-error
    - libksba-devel
    - libpth-devel
    - pinentry
rundeps :
    - pinentry
setup      : |
    %configure --enable-symcryptrun --enable-gpgtar --enable-standard-socket
build      : |
    %make
install    : |
    %make_install DESTDIR=$installdir
    ln -s /usr/bin/gpg2 $installdir/usr/bin/gpg
